### ISSUE TITLE
CATALINA_HOME in /etc/defaults/tomcat7 is blank on Ubuntu 14.04

### ISSUE THREAD

**Issue by etlweather** [antoineco/aco-tomcat#1]
I applied this module like so to a node:

``` puppet
class {'::tomcat':
  install_from => 'package',
  version      => '7',
}
```

The package installs properly on Ubuntu 14.04 server. However, the defaults file (`/etc/default/tomcat7`) has all blank variables (`CATALINA_BASE`, `CATALINA_HOME`, `JASPER_HOME`, etc).
As a result, running `service tomcat7 start` or `/etc/init.d/tomcat7 start` causes an error stating that `tomcat7 is not installed`. 
That's because `CATALINA_HOME` is blank and the script isn't able to confirm that files are present in `CATALINA_HOME`.
Event if I set this those variables, I still get the same result in the defaults file.
I'm using version 0.5.3 of the module.

**Comment by antoineco** [comment]
Hi, and thanks for the report!

When you install from package and want to override the default version (tomcat 8.0.9 in Ubuntu 14.10 if I remember well) you have to override both the version and the package name, like this:

``` puppet
class { '::tomcat':
  install_from => 'package',
  version      => '7.0.55',
  package_name => 'tomcat7',
}
```

You can see all available versions for your distribution inside the params.pp file.

Does it solve the issue?

**Comment by antoineco** [comment]
Sorry I misread, you're using Ubuntu 14.04. This distribution already has tomcat 7 as the default, so you can just leave the version and package name to their default values:

``` puppet
include ::tomcat
```

equals to this on Ubuntu 14.04:

``` puppet
class { '::tomcat':
  install_from => 'package',
  version      => '7.0.52',
  package_name => 'tomcat7',
}
```

(moreover the 'version' parameter should always be formated like 'x.y.z', not just '7' like you did in the example)

**Comment by etlweather** [comment]
Thanks. However, other than the blank variables in the defaults file, everything worked. My system did not have Tomcat already installed. Puppet installed it through your module with version 7. 

I want to specify version 7 as this is what is tested with the web application so if the OS was to now have version 8 as default, I still would want version 7 until version 8 is tested with the application.

Everything, except the default file, worked when I specified version "7".

I made this work for me by doing this change:
https://github.com/etlweather/aco-tomcat/compare/tOnI0:master...etlweather:etlweather-fix

But I'm still just learning Puppet so maybe that is not the correct solution. I'm going to try specifying a 3-digits version number see if that solves the problem.

**Comment by etlweather** [comment]
I tried specifying the version as 7.0.52 and the `/etc/defaults/tomcat7` still ends up with blank variables. I'm running Puppet v3.7.3

**Comment by antoineco** [comment]
Hm, I can not reproduce it.

It seems like something is messing with your scope. Defining the full scope like you did will work for the main instance but will break the template if multiple instances are deployed on the same machine (they will all end up with the same config file)

Can you tell me more about your setup? What happens if you output these problematic variables using a 'notify' resource?

Thanks for your feedback!

**Comment by tOnI0** [comment]
Hm, I can not reproduce it.

It seems like something is messing with your scope. Defining the full scope like you did will work for the main instance but will break the template if multiple instances are deployed on the same machine (they will all end up with the same config file)

Can you tell me more about your setup? What happens if you output these problematic variables using a 'notify' resource?

Thanks for your feedback!

**Comment by etlweather** [comment]
I'm trying to implement the concept of Roles and Profiles (http://www.craigdunn.org/2012/05/239/ and https://puppetlabs.com/learn/roles-profiles-introduction ). So I set up classes like so:

``` puppet
class profile::base {
  include ntp
}

class profile::jdk7 {
  class { 'java':
    package => 'openjdk-7-jdk',
  }
}

class profile::tomcat7 {
   class {'::tomcat':
      install_from    => 'package',
      version         => '7.0.52',
      catalina_home   => '/usr/share/tomcat7',
      catalina_base   => '/var/lib/tomcat7',
   }
}

class profile::tomcat7jdk7 {
  include profile::jdk7
  include profile::tomcat7
}

class role::base {
  include profile::base
}

class role::webappserver inherits role::base {
   include profile::tomcat7jdk7
}
```

And in Hiera, I assign the class `webappserver` to my node.

If I output the variable in the `config.pp` file like so:

``` puppet

  notify { "::tomcat::catalina_home_real=${::tomcat::catalina_home_real}":}
  notify { "::catalina_home_real=${::catalina_home_real}":}
  notify { "catalina_home_real=${catalina_home_real}":}

  file { 'tomcat environment variables':
     .....
```

I get:

```
Notice: catalina_home_real=
Notice: ::tomcat::catalina_home_real=/usr/share/tomcat7
Notice: ::catalina_home_real=
```

Thanks for your help so far. Outside this minor issue I ran into, your module was the easiest to use out of the 4 Tomcat modules I tried so far.

**Comment by antoineco** [comment]
OK, the output of the 'notify' is logic. Still I can't reproduce the issue using the exact same code as you use.

Are you sure you don't have any 'catalina_home' or 'catalina_base' variables defined somewhere in Hiera or some top level class?

Have you tried to declare the class in a node definition or even locally using "puppet apply -e 'include tomcat'" for example?

**Comment by antoineco** [comment]
I would be very grateful if you could add this resource to your 'profile::tomcat7' class, and send me the "/tmp/scope.yaml" file per email.

``` puppet
file { "/tmp/scope.yaml":
  content => inline_template("<%= scope.to_yaml %>"),
  require => Class['tomcat']
}
```

Thank you in advance!

**Comment by etlweather** [comment]
I sent you an email with the scope file. 

I also tried it using a node definition and it gave the same result, empty variables in the defaults file.

**Comment by antoineco** [comment]
Did you enable the future parser by any chance?

**Comment by etlweather** [comment]
Hum... I did, I forget why I did that.

**Comment by antoineco** [comment]
Well, that's the cause of the problem :) However I will definitely have to take a look into it, Puppet 4.0 is coming and I'd like my modules to be compatible with it.

Just for the confirmation, could you try to disable it?

**Comment by etlweather** [comment]
I checked this out and turning the future parse off did the trick.

I found why I turned it on in the first place ( https://docs.puppetlabs.com/puppet/3.7/reference/dirs_manifest.html#directory-behavior-vs-single-file ) - I wanted Puppet to traverse sub-directories.

But I can live with a flat manifests directory for now.

**Comment by antoineco** [comment]
Here is a conversation about the future parser and its new bahaviour toward the scope: https://groups.google.com/forum/#!topic/puppet-users/s2qHrypfX44

The future parser will be fully supported in the version 0.6 of the module. Thanks again for your feedback!
