### ISSUE TITLE
Support more context.xml parameters

### ISSUE THREAD

**Issue by hanej** [antoineco/aco-tomcat#10]
Please allow more context elements in context.xml.  Right now the only thing we can add are ResourceLink elements.  We need to be able to also add attributes to the root <Context> element.

**Comment by antoineco** [comment]
Definitely on the roadmap. Could you suggest some elements to start with?

**Comment by hanej** [comment]
We specifically need to be able to set attributes to the root <Context>
node (like useHttpOnly="false"), manage the Manager element (for right
now just enable and disable session persistence) and the ability to
specify additional contexts.

**Comment by antoineco** [comment]
This commit adds a couple of parameters to configure the main Context:

```
$context_params             = {},
$context_loader             = {},
$context_manager            = {},
$context_realm              = {},
$context_resources          = {},
$context_parameters         = [],
$context_environments       = [],
$context_listeners          = [],
$context_valves             = [],
$context_resourcelinks      = [],
```

Specifying additional contexts will require some extra efforts though (I will probably have to create a custom `define`)

**Comment by antoineco** [comment]
@hanej did you find the time to test this?

**Comment by hanej** [comment]
Sorry.  I didn't realize this was ready.  I'll start testing.

**Comment by hanej** [comment]
Looks like there is no ensure on the file resource which is causing the context.xml to be created as a directory.  I had to update instance.pp and config.pp to ensure => 'file'.

**Comment by hanej** [comment]
The same thing with the service files in /etc/init.d.  They are being created as directories too.

**Comment by antoineco** [comment]
Strange behavior, don't you have a `File { ensure => directory }` defined
somewhere?

**Comment by antoineco** [comment]
v1.0.0 was released today with the current changes, but I'll leave the ticket open for now.

**Comment by antoineco** [comment]
Hey @hanej, are you already using the context.xml customization features from the module? Do you have any feedback already? You mentioned you wanted to be able to configure extra contexts, anything you can not do on a per-app basis?

**Comment by hanej** [comment]
Yes.  It works great except for it is now missing the `<WatchedResource>` element.  Other than that I think we're good with this. Thanks!

```
<!-- Default set of monitored resources -->
<WatchedResource>WEB-INF/web.xml</WatchedResource>
```

**Comment by antoineco** [comment]
Problem solved :)

**Comment by hanej** [comment]
That did the trick.  Thanks!
