### ISSUE TITLE
Provide link for donations

### ISSUE THREAD

**Issue by hanej** [antoineco/aco-tomcat#11]
This module is a stellar example of how to design and test Puppet modules and listen to community feedback.  This is a great open source project.  You should have a donate button in the Forge.

**Comment by antoineco** [comment]
Thanks Jason, I really appreciate the message !

A "thank you" is however more than enough to support my work. If I was
working on it more than 4 hours per week and had 90% of code coverage in my
tests I could possibly argue, but not in the current state.

If you want to help please keep on suggesting improvements, that's the best
way to make my module as useful and usable as possible :)

Cheers
