### ISSUE TITLE
Duplicate user/group declaration

### ISSUE THREAD

**Issue by hanej** [antoineco/aco-tomcat#12]
We have to specify a specific uid/gid for our local users and groups so we maintain those in virtual resources.  On line 15 of archive.pp, it tries to create the user and group.  Could you replace those lines with an ensure_resource from stdlib or check to see if they are already defined?

**Comment by hanej** [comment]
Or even a setting to disable management of local user and group would be fine.

**Comment by antoineco** [comment]
Done, thanks for the suggestion :+1:
