### ISSUE TITLE
archive startup Tomcat6 + pid file present - failure

### ISSUE THREAD

**Issue by mdimarino** [antoineco/aco-tomcat#16]
Hello, there is a problem using tomcat archive and aco-tomcat module.

Because pid file should always be present in archive install mode it breaks startup.sh and shutdown.sh scritps.

www@web02:~/tomcat/temp$ ll
total 8
drwxr-xr-x 2 www www 4096 Mai 23 11:04 ./
drwxr-xr-x 8 www www 4096 Mai 23 11:01 ../
-rw-r--r-- 1 www www    0 Jul 19  2010 safeToDelete.tmp
-rw-r--r-- 1 www www    0 Mai 23 11:04 tomcat6.pid
www@web02:~/tomcat/temp$ ../bin/startup.sh 
Using CATALINA_BASE:   /www/tomcat
Using CATALINA_HOME:   /www/tomcat
Using CATALINA_TMPDIR: /www/tomcat/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /www/tomcat/bin/bootstrap.jar
PID file (/www/tomcat/temp/tomcat6.pid) found. Is Tomcat still running? Start aborted.
www@web02:~/tomcat/temp$ ps fauxww | grep java
www       3187  0.0  0.0  10464   932 pts/0    S+   11:14   0:00                              _ grep --color=auto java
# 

My site.pp:

   include apt

   apt::ppa { "ppa:webupd8team/java": }

   class { 'app_users': } ->
   exec { "accept_license":
       command => "echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections",
       cwd  => "/root",
       user => "root",
       path => "/usr/bin/:/bin/",
       before => Package["oracle-java6-installer"],
       logoutput => true,
   } ->
   package { "oracle-java6-installer":
       ensure => present,
   } ->
class { '::tomcat':
  install_from => 'archive',
  version      => '6.0.29',
  catalina_base => '/www/tomcat',
  catalina_home => '/www/tomcat',
  tomcat_user => www,
  tomcat_group => www,
  catalina_pid => '/www/tomcat/temp/tomcat6.pid',
  service_ensure => stopped,
}

**Comment by antoineco** [comment]
Hi Marcello, thanks for reporting, I'm taking a look into it

**Comment by mdimarino** [comment]
Changing ensure from 'present' to 'file' made it works for me. 

  # pid file management
  if $::tomcat::install_from == 'archive' {
    file { "instance ${name} pid file":
      ensure => file,
      path   => $catalina_pid_real
    }

**Comment by antoineco** [comment]
I don't think that's the real source of the issue, I should actually not force the creation of the pid file. Originally I did it to bypass a permission issue when using `/var/run` as the pid directory (owned by root, aouch), but I have a commit on the way to fix that.

Check it out, and give me your feedback if you can.

**Comment by antoineco** [comment]
Changes released in v1.0.3

**Comment by antoineco** [comment]
@mdimarino can you confirm that 1.0.3 fixes your issue?

**Comment by mdimarino** [comment]
Working fine!
