### ISSUE TITLE
Redundant AJP connectors in instance server.xml

### ISSUE THREAD

**Issue by joshuabaird** [antoineco/aco-tomcat#22]
I am invoking tomcat and tomcat::instance like so:

```
class { '::tomcat':
  package_name   => $tomcat_package,
  catalina_home  => $tomcat_catalina_home,
  admin_webapps  => $tomcat_admin_webapps,
  service_ensure => 'stopped',
  service_enable => false,
}

 tomcat::instance { $default_instance_name:
   root_path           => $default_instance_root_path,
   server_control_port => $default_instance_control_port,
   ajp_connector       => true,
   ajp_port            => $default_instance_ajp_port,
   ajp_protocol        => 'AJP/1.3',
   java_home           => $default_instance_java_home,
   admin_webapps       => false,
 }
```

This results in $CATALINA_BASE/conf/server.xml containing two "connectors" for 8081:

```
# grep 8081 server.xml
    <Connector port="8081" />
    <Connector port="8081" protocol="AJP/1.3" />
```

This is breaking the AJP connector.  If I remove the first "connector" everything works normally.  Any ideas?

**Comment by antoineco** [comment]
Yup, that's because a HTTP connector is [enabled by default](https://github.com/antoineco/aco-tomcat/blob/master/manifests/instance.pp#L114-116), and set to listen on port 8081, hence the conflict with your AJP connector.

Set `http_connector => false` and you'll be good to go :+1:

**Comment by joshuabaird** [comment]
Ah, ha!   Thanks!  Problem solved.
