### ISSUE TITLE
Implement $package_version or something similar

### ISSUE THREAD

**Issue by joshuabaird** [antoineco/aco-tomcat#23]
I'm looking to ensure that a certain version of a Tomcat package is installed on RHEL.  Something like this would work:

```
package { $package_name;
  ensure => $package_version,
}
```

Currently, the 'package' resource is ensuring `present`

**Comment by antoineco** [comment]
Just for the sake of making public the answer I gave you by email I'm also going to write a comment here.

The reason why I did not ensure package_version = $version is because rpm (RedHad) and apt (Debian) have different versioning conventions.
On RedHat it would be enough to use:

```
package { 'tomcat server':
  ensure => '7.0.56',
  name   => 'tomcat7'
}
```

While on Debian you would **have** to set (note the version suffix):

```
package { 'tomcat server':
  ensure => '7.0.56-3',
  name   => 'tomcat7'
}
```

Not very portable.

Puppet will happily accept a wildcard in the $version parameter but will then send you notices such as `Notice: /Stage[main]/Main/Package[tomcat server]/ensure: ensure changed '7.0.56-3' to '7.0.56*'` on every run. Yet another issue.

I usually recommend people who need a specific tomcat version (understand _other than the ones available inside their distro repositories_) to use `install_from => 'archive'`. This has the advantage of pulling everything directly from archive.apache.org, whatever the OS and whatever the repositories enabled on the target system. Could that be an option for you?

**Comment by joshuabaird** [comment]
Hmm, I actually use something like `ensure => 6.0.41-4.el6` when specifying versions for RedHat.  Maybe I'm providing too much information, but I think the iteration is important since there can be multiple iterations of one package in a single repo.

Even if I am using RPMs provided by a repo like Ulyaoth, `ensure => present` would give me the latest package in the repo, when I may require a slightly older version (6.0.41 in my case).  Installing from an archive does make this a bit easier, but unfortunately, using RPMs for packaging is a requirement.

**Comment by antoineco** [comment]
Alright then, feature request accepted :+1:

**Comment by antoineco** [comment]
That should solve it.

The module now accepts `x.y.z[-package_suffix]` as tomcat version and ensures the package version is set to this value. It also performs a string extraction in order to use only the real tomcat version (`x.y.z`) where needed.

Before merging and pushing changes to the Forge I need:
1. to adjust the package version strings accordingly in [manifests/params.pp](https://github.com/antoineco/aco-tomcat/blob/master/manifests/params.pp)
2. your feedback

**Comment by antoineco** [comment]
Btw @joshuabaird, when you write "using RPMs for packaging is a requirement." do you mean that packages MUST be installed from RPM on your system, or just that packaging your tomcat as tar archive is not an option. 

I just want to make it clear that with this module you don't have to package your own tomcat, it will fetch everything from the public Apache Archives. 

This was just a parenthesis.

**Comment by joshuabaird** [comment]
@antoineco, all software must be packaged (using RPM) in our environment.  I'll take a look at your new code and let you know!  Thanks!

**Comment by joshuabaird** [comment]
Should the module be creating an init script for my instance?

```
Error: /Stage[main]/Tomcat::Install::Package/File_line[fix broken tomcat init script]: Could not evaluate: No such file or directory - /etc/init.d/aspen-tomcat6
Notice: /Stage[main]/Tomcat::Config/File[tomcat environment variables]: Dependency File_line[fix broken tomcat init script] has failures: true
```

There is this invalid symlink in /etc/init.d:

`lrwxrwxrwx  1 root root     7 Jul 17 13:19 tomcat6_default -> tomcat6`

(/etc/init.d/tomcat6 does not exist, but /etc/init.d/tomcat does)

**Comment by antoineco** [comment]
No it doesn't because package managers are expected to deploy init scripts / systemd units. Puppet should never override a script deployed by a package.

Regarding the symlink it depends, I assume you created another instance called default?

**Comment by joshuabaird** [comment]
Yes, but a package cannot install an init script for a custom instance deployed by the module, right?  It looks like there is code in the logic to create a symlink for each instance?  Yes, I create an instance named 'default' and another instance.

**Comment by antoineco** [comment]
Yes because tomcat init scripts from all Linux distributions support multi instance configuration. If you take a look at one of them you'll see that the name of the instance is derived from the basename of the init script, making it designed to be symlinked.

This is actually documented by Apache (sometimes in the script itself), and it's the reason why I'm doing it that way.

**Comment by joshuabaird** [comment]
Ok, sorry, I misunderstood how that was designed.  It looks like the init script provided by the Ulyaoth repository [1] doesn't include this functionality (which is what I am using).  My package was built using the Ulyaoth SPEC, but was renamed to 'aspen-tomcat6'.

It looks like the module is trying to manipulate /etc/init.d/aspen-tomcat6 (the package name).  Does this sound right?  Regardless, no symlink is being created for the init script.

[1] https://github.com/sbagmeijer/ulyaoth/blob/master/Repository/ulyaoth-tomcat/SOURCES/tomcat.init

**Comment by antoineco** [comment]
That's right, Ulyaoth doesn't support multi-instance, on top of that it uses a hard-coded TOMCAT_HOME variable instead of CATALINA_HOME, I never paid attention to that.

Good point, I should submit a push request because I'm using it as an example in my documentation. 

Since you're packaging your own rpm I think using the plain init script distributed by RedHat would be enough to make it work.

**Comment by antoineco** [comment]
Oh, and the script manipulation was here to fix a bug in a very specific version of tomcat6 on CentOS 6. I could probably remove it now, since it was fixed last year.

**Comment by joshuabaird** [comment]
Ok - but even with the RHEL 'tomcat' init script, the module is failing to create the symlink.  It immediately tries to use 'fix broken init script' to manipulate /etc/init.d/aspen-tomcat6 (which does not exist).  I'm not even sure it should exist with that name, since that is not the name of the instance, but the name of the package.

Sorry for the back and forth!

**Comment by joshuabaird** [comment]
This is how I am invoking 'tomcat':

```
 # Install Tomcat, but disable the global/main instance.
    class { '::tomcat':
      package_name   => $tomcat_package,
      version        => $tomcat_package_version,
      catalina_home  => $tomcat_catalina_home,
      admin_webapps  => $tomcat_admin_webapps,
      service_ensure => 'stopped',
      service_enable => false,
    }
```

I then deploy my own 'defualt' instance:

```
 # Configure the default Tomcat instance
 tomcat::instance { $default_instance_name:
   root_path           => $default_instance_root_path,
   server_control_port => $default_instance_control_port,
   ajp_connector       => true,
   ajp_port            => $default_instance_ajp_port,
   ajp_protocol        => 'AJP/1.3',
   http_connector     => false,
   java_home           => $default_instance_java_home,
   admin_webapps       => false,
 }
```

**Comment by antoineco** [comment]
Could that be of any interest for you? [Rhel6 tomcat6 SRPM](http://ftp.redhat.com/redhat/linux/enterprise/6Server/en/os/SRPMS/tomcat6-6.0.24-83.el6_6.src.rpm)

**Comment by antoineco** [comment]
If you rename your package you also have to use $service_name = tomcat6, since it défauts to $package_name

**Comment by joshuabaird** [comment]
The init script is /etc/init.d/tomcat (and service_name => tomcat), so why is the module creating symlinks named 'aspen-tomcat6_default'?

**Comment by antoineco** [comment]
Because the service name of all instances derives from the package name, it means you have to set $service_name for every instance (or name your package "tomcat")

Let's take an example: if my package is called `foo_tomcat6`, the service name will default to `foo_tomcat6` for the main instance, and `foo_tomcat6_instance2` for my `instance2`.
This comes from the fact that on RedHat tomcat services are named after the package name, so I set my default to these values.

Now, if you rename your services to `tomcat_instance1` (make sure `/etc/init.d/tomcat_instance1` exists!) and `tomcat_instance2`, symlinks will be generated as follows: `/etc/init.d/tomcat_instance2 -> /etc/init.d/tomcat_instance1`

**Comment by joshuabaird** [comment]
Ok, that makes sense.  I'll just set `service_name` on each instance.  Looks like I just need to modify the default RHEL init script a bit and this should start working.

**Comment by antoineco** [comment]
The main point is generally to have a init script matching your package name, and supporting [multi-instance configuration](http://tomcat.apache.org/tomcat-8.0-doc/RUNNING.txt). If both these conditions are met you do not even need to fiddle with service names.

**Comment by antoineco** [comment]
So, regarding your comment in the Ulyaoth repo, seems like we're getting there!

I noticed that your start command is

``` sh
$SU - $TOMCAT_USER -c "cd $CATALINA_HOME/bin && $CATALINA_HOME/bin/startup.sh"
```

but you should also at least export your CATALINA_BASE:

``` sh
$SU - $TOMCAT_USER -c "export CATALINA_BASE=$CATALINA_BASE; cd $CATALINA_HOME/bin && $CATALINA_HOME/bin/startup.sh"
```

---

I just gave it a try with the "official" tomcat6 distributed on CentOS 6, and can confirm multi-instance works there.

Manifest:

``` puppet
include tomcat

tomcat::instance { 'instance1':
  server_control_port => 8006,
  http_port           => 8081,
  ajp_connector       => false
}
tomcat::instance { 'instance2':
  server_control_port => 8007,
  http_port           => 8082
}
```

Init scripts:

``` sh
# ls -l /etc/init.d/tomcat*
-rwxr-xr-x. 1 root root 7536 Jul 21 06:14 /etc/init.d/tomcat6
lrwxrwxrwx. 1 root root    7 Jul 21 06:14 /etc/init.d/tomcat6_instance1 -> tomcat6
lrwxrwxrwx. 1 root root    7 Jul 21 06:14 /etc/init.d/tomcat6_instance2 -> tomcat6
```

Process list:

``` sh
# ps axjfww
 PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
    0     1     1     1 ?         2771 Ss       0   0:00 /bin/bash
    1  2473  2449  2449 ?           -1 Sl      91   0:01 /usr/lib/jvm/jre/bin/java -server -classpath :/usr/share/tomcat6/bin/bootstrap.jar:/usr/share/tomcat6/bin/tomcat-juli.jar:/usr/share/java/commons-daemon.jar -Dcatalina.base=/var/lib/tomcats/instance1 -Dcatalina.home=/usr/share/tomcat6 -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/tomcats/instance1/temp -Djava.util.logging.config.file=/var/lib/tomcats/instance1/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager org.apache.catalina.startup.Bootstrap start
    1  2593  2569  2569 ?           -1 Sl      91   0:01 /usr/lib/jvm/jre/bin/java -server -classpath :/usr/share/tomcat6/bin/bootstrap.jar:/usr/share/tomcat6/bin/tomcat-juli.jar:/usr/share/java/commons-daemon.jar -Dcatalina.base=/var/lib/tomcats/instance2 -Dcatalina.home=/usr/share/tomcat6 -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/tomcats/instance2/temp -Djava.util.logging.config.file=/var/lib/tomcats/instance2/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager org.apache.catalina.startup.Bootstrap start
    1  2737  2713  2713 ?           -1 Sl      91   0:01 /usr/lib/jvm/jre/bin/java -server -classpath :/usr/share/tomcat6/bin/bootstrap.jar:/usr/share/tomcat6/bin/tomcat-juli.jar:/usr/share/java/commons-daemon.jar -Dcatalina.base=/usr/share/tomcat6 -Dcatalina.home=/usr/share/tomcat6 -Djava.endorsed.dirs= -Djava.io.tmpdir=/usr/share/tomcat6/temp -Djava.util.logging.config.file=/usr/share/tomcat6/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager org.apache.catalina.startup.Bootstrap start
```

---

Here is the full script: [/etc/init.d/tomcat6](https://gist.github.com/antoineco/97e782e18bb9efb19d22#file-tomcat6-sh). 
This one is using a [parseOptions() function](https://gist.github.com/antoineco/97e782e18bb9efb19d22#file-tomcat6-sh-L81-95) to `export` the options from the sysconfig file. Could be another clean alternative for you.

**Comment by joshuabaird** [comment]
Did you use that script with the Ulyaoth packages?  It would need to be modified a bit more to work there.

**Comment by antoineco** [comment]
Yes obviously it needs to be adapted, but from what I checked the Ulyaoth script only requires a very tiny modification in order to work as the module expects. If you source the config file and export $CATALINA_BASE, as suggested in my previous comment, startup.sh will do the rest.

RedHat scripts are reliable but unnecessarily complex in my opinion.

**Comment by joshuabaird** [comment]
Yeah, it may be overly complex (the RHEL script).  I'm working with the RHEL script at the moment, and I made the following changes:
- TOMCAT_CFG=/opt/tomcat/conf/tomcat.conf (empty really)
- TOMCAT_SCRIPT=/opt/tomcat/bin/catalina.sh

This allows "start" and "status" to work, but "stop" seems to be broken:

```
root@aspdv-d1-ap01:/etc/init.d# service tomcat_aspen stop
Stopping tomcat_aspen: Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
ERROR: List of process IDs must follow --pid.
********* simple selection *********  ********* selection by list *********
-A all processes                      -C by command name
-N negate selection                   -G by real group ID (supports names)
-a all w/ tty except session leaders  -U by real user ID (supports names)
-d all except session leaders         -g by session OR by effective group name
-e all processes                      -p by process ID
                                      -q by process ID (unsorted & quick)
T  all processes on this terminal     -s processes in the sessions given
a  all w/ tty, including other users  -t by tty
g  OBSOLETE -- DO NOT USE             -u by effective user ID (supports names)
r  only running processes             U  processes for specified users
x  processes w/o controlling ttys     t  by tty
*********** output format **********  *********** long options ***********
-o,o user-defined  -f full            --Group --User --pid --cols --ppid
-j,j job control   s  signal          --group --user --sid --rows --info
-O,O preloaded -o  v  virtual memory  --cumulative --format --deselect
-l,l long          u  user-oriented   --sort --tty --forest --version
-F   extra full    X  registers       --heading --no-heading --context
                                      --quick-pid
                    ********* misc options *********
-V,V  show version      L  list format codes  f  ASCII art forest
-m,m,-L,-T,H  threads   S  children in sum    -y change -l format
-M,Z  security data     c  true command name  -c scheduling class
-w,w  wide output       n  numeric WCHAN,UID  -H process hierarchy
/etc/init.d/tomcat_aspen: line 163: [: : integer expression expected
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
ERROR: List of process IDs must follow --pid.
```

I'll try modifying the simple Ulyaoth script.

**Comment by antoineco** [comment]
I did a slight modification to Ulyaoth's script. Would you mind trying?
https://gist.github.com/antoineco/97e782e18bb9efb19d22#file-tomcat_ulyaoth_fixed-sh

**Comment by joshuabaird** [comment]
We need this snippet (and $SU):

```
if [ -x "/sbin/runuser" ]; then
    SU="/sbin/runuser -s /bin/sh"
else
    SU="/bin/su -s /bin/sh"
fi
```

Otherwise we get this since the `tomcat` user has a shell of `/sbin/nologin`:

```
root@aspdv-d1-ap01:/etc/init.d# service tomcat_aspen start
Starting tomcat
This account is currently not available.
```

After these changes, the instance starts:

```
root@aspdv-d1-ap01:/etc/init.d# service tomcat_aspen start
Starting tomcat
Using CATALINA_BASE:   /srv/tomcat/aspen
Using CATALINA_HOME:   /opt/tomcat
Using CATALINA_TMPDIR: /srv/tomcat/aspen/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /opt/tomcat/bin/bootstrap.jar
root@aspdv-d1-ap01:/etc/init.d# ps aux | grep java
tomcat   22694 47.5  2.8 1802044 55508 ?       Sl   09:36   0:01 /usr/bin/java -Dnop -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.endorsed.dirs=/opt/tomcat/endorsed -classpath /opt/tomcat/bin/bootstrap.jar -Dcatalina.base=/srv/tomcat/aspen -Dcatalina.home=/opt/tomcat -Djava.io.tmpdir=/srv/tomcat/aspen/temp org.apache.catalina.startup.Bootstrap start
root     22714  0.0  0.0 103248   836 pts/0    S+   09:36   0:00 grep java
```

'status' also works:

```
root@aspdv-d1-ap01:/etc/init.d# service tomcat_aspen status
Tomcat is running with pid: 22694
```

And 'stop' works as well:

```
root@aspdv-d1-ap01:/etc/init.d# service tomcat_aspen stop
Stoping Tomcat
Using CATALINA_BASE:   /srv/tomcat/aspen
Using CATALINA_HOME:   /opt/tomcat
Using CATALINA_TMPDIR: /srv/tomcat/aspen/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /opt/tomcat/bin/bootstrap.jar
Waiting for processes to exit. Timeout before we kill the pid: 0/30
```

I think we are making progress!

**Comment by antoineco** [comment]
:tada:
I updated the Gist with your suggestion.

**Comment by joshuabaird** [comment]
Perfect, thanks!  I also posted something (I didn't see that you had) with a few other modifications.

One more issue that I am noticing:

`Notice: /Stage[main]/Tomcat::Service::Package/Service[aspen-tomcat6]/ensure: ensure changed 'running' to 'stopped'`

This happens each Puppet run.  The module is successfully managing my other instances (`aspen-tomcat6_default` and `aspen-tomcat6_aspen`).  I intend to have the 'global' `aspen-tomcat6` instance disabled (not running or enabled).  It is not running, but Puppet keeps trying to stop it.

```
root@aspdv-d1-ap01:/etc/init.d# service aspen-tomcat6 status
aspen-tomcat6 is not running
```

I did notice that if I remove `service_ensure => stopped` from the `::tomcat` declaration, that this 'problem' goes away, so maybe that is the solution.

**Comment by antoineco** [comment]
That's a Puppet thing: the status() function of your script always returns 0, so Puppet assumes the service is running whereas it's not.
Here is a quick fix: https://gist.github.com/antoineco/97e782e18bb9efb19d22/revisions?diff=split

The `exit 3` code comes from here: http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html.

Could be nice to handle pid file cleanup if tomcat exited unexpectedly. [Here is some inspiration](https://gist.github.com/antoineco/97e782e18bb9efb19d22#file-tomcat6-sh-L189-211).

**Comment by joshuabaird** [comment]
Ok - thanks.  Now I'm having another problem that I can't seem to figure out.

I stuck `sample.war` in $CATALINA_BASE/webapps of one of my instances, it was auto-deployed correctly (verified via logs), but I'm unable to access anything due to 404 errors.

I can't figure out why Tomcat is throwing the 404 since the files are clearly there.  Any ideas on how to debug this?  I realize this may be outside of the module, but everything worked fine when I was using the old Tomcat module, so maybe you have an idea.

I think it may be because $CATALINA_BASE/conf/web.xml is missing?

EDIT:  Yes, when I copied $CATALINA_HOME/conf/web.xml to $CATALINA_BASE/conf/web.xml, everything started working.  It doesn't look like there is anything in the module to drop this file down, perhaps it should be loaded from $CATALINA_HOME but it's not for some reason?

Again, thanks for all of the help!

**Comment by antoineco** [comment]
I wish I could help but that's not something I can answer without seeing the package unfortunately. It could be a context misconfiguration since this module inherits from the default `context.xml` from tomcat8, but I doubt this file changed since tomcat5. 

I'd suggest to remove context.xml and try again, enabling the AccessLogValve can also certainly help.

**Comment by joshuabaird** [comment]
Ok - FYI, it's the Ulyaoth tomcat6 package, and all it does is extract the archive from tomcat.apache.org into /opt/tomcat.  I'm not sure if Tomcat6 needs a separate web.xml in $CATALINA_BASE/conf, or if it should fall back to $CATALINA_HOME/conf/web.xml.

**Comment by antoineco** [comment]
I'm quite certain tomcat never falls back when it comes to the conf directory. Does your app contain its own web.xml?

**Comment by antoineco** [comment]
Just to confirm what I wrote about the context, the default for tomcat6 is:

``` xml
<WatchedResource>WEB-INF/web.xml</WatchedResource>
```

and this module sets

``` xml
<WatchedResource>WEB-INF/web.xml</WatchedResource>
<WatchedResource>${catalina.base}/conf/web.xml</WatchedResource>
```

This can be configured using the `context_watchedresources` parameter, just in case this is the cause of your issue.

**Comment by joshuabaird** [comment]
All good here, thanks!

**Comment by antoineco** [comment]
You're welcome! Btw the issue was closed automatically when I merged the feature but feel free to keep asking questions here if you feel like.

**Comment by joshuabaird** [comment]
One last thing:

Let's say I want to run the RHEL7 tomcat package (which is currently 7.0.54-2.el7_1 as defined in params.pp).  However, a new patch version comes out during the next round of RHEL updates - let's say it's 7.0.54-3.el7_1.  Out of band updates may cause this package to get updated, but the aco-tomcat module is still trying to require an old version (7.0.54-2).  This will make the Puppet run fail.  Should we simply allow 'present' for $version (as well as specific versions)?

**Comment by antoineco** [comment]
It will fail if you run it on a fresh system indeed, but if tomcat is already installed it won't do anything. It's a trade-off between control and usability, I can offer to push changes as soon as they make it to the repo if this is really an issue, and I'll be happy to merge contributions from active users if I miss an update.

`present` can't be used since the version number is used to fetch extra librairies with the correct version.

**Comment by antoineco** [comment]
Regarding out of the band updates, the practice is strongly discouraged if your package is managed by a configuration management system. Most package managers provide exclusion lists, but I could think about something to cover both scenarios indeed.
