### ISSUE TITLE
Multi-user support for instances

### ISSUE THREAD

**Issue by joshuabaird** [antoineco/aco-tomcat#25]
I have a use-case that requires that tomcat::instance supports `tomcat_user` and `tomcat_group`.  I need the instance to run as a unique user, but not globally.

**Comment by antoineco** [comment]
This commit creates the user/group if not present and applies the right permissions on the filesystem. I still have to update a couple of ERB files to make the service run as the defined user/group.

**Comment by joshuabaird** [comment]
Opened #27 to update the ERB templates for the systemd units.

**Comment by antoineco** [comment]
I think we're good to go, would you mind giving it a quick try just in case I missed something?

**Comment by joshuabaird** [comment]
I just tested and it looks good :+1:
