### ISSUE TITLE
DefaultServlet missing in secondary instances

### ISSUE THREAD

**Issue by antoineco** [antoineco/aco-tomcat#26]
A default web.xml should be created with every instance.

**Comment by antoineco** [comment]
Ready for review, see new parameter in [instance.pp](https://github.com/antoineco/aco-tomcat/blob/670224d0c073d30c9a43e79a273e5039598c7879/manifests/instance.pp#L205)

**Comment by antoineco** [comment]
@joshuabaird this might interest you.

**Comment by joshuabaird** [comment]
This is great, thanks!
