### ISSUE TITLE
tomcat::install resources are not contained.

### ISSUE THREAD

**Issue by chris-bmj** [antoineco/aco-tomcat#30]
I had to add the line "contain 'tomcat::install'" to line 514 of init.pp otherwise the module does not contain these resources, potentially causing problems.
Cheers.

**Comment by chris-bmj** [comment]
Actually ended up looking like this:

```
# start the real action
  class { 'tomcat::install': }
  contain 'tomcat::install'

  class { 'tomcat::service':
    require => Class['::tomcat::install']
  }

  class { 'tomcat::config':
    require => Class['::tomcat::install']
  }
```

**Comment by antoineco** [comment]
Hey Chris, thanks for reporting this.

Containing classes is a good idea, I did not judge it necessary here because all sub-classes are private and strictly ordered in the main class. Could you describe in what situation you faced issues?

**Comment by chris-bmj** [comment]
Yes of course. I use an 'accounts' module to create users and groups.  This module needs to be run before any other modules which install packages that create users or groups.

I use the roles/profiles model and force ordering in this case in a role which contains 'profile::base' (which contains the accounts module) and 'profile::tomcat' (which contains your tomcat module).  The role manifest forces the former to run before the latter.

This didn't work as expected though as tomcat kept getting installed before the accounts module had run.  Not all the tomcat classes -- just the tomcat::install class.
Adding those lines to contain the install class now forces tomcat::install to run at the same time as the rest of the tomcat classes, after the accounts module.

Ta

**Comment by antoineco** [comment]
Makes sense, I'll add it shortly. Thanks again for the suggestion.
