### ISSUE TITLE
Include default generic web.xml

### ISSUE THREAD

**Issue by joshuabaird** [antoineco/aco-tomcat#31]
We had talked about this a month or so ago.  Is it a good idea to bundle a default (generic) web.xml for applications who may not include their own?  I'm dealing with an app that does not contain it's own web.xml right now, and I had to manually drop one.

**Comment by antoineco** [comment]
Hey @joshuabaird, there is already an open issue for this: #26 
I haven't found the free time to work on it yet, I know I'm very slow. It seems to be doable tomorrow for me though.

**Comment by joshuabaird** [comment]
Oops!  Sorry, now sure how I missed that.
