### ISSUE TITLE
Incorrect permissions on context.xml

### ISSUE THREAD

**Issue by joshuabaird** [antoineco/aco-tomcat#32]
When using `tomcat_user` and `tomcat_group` on `tomcat::instance`, the owner of $CATALINA_BASE/conf/context.xml is being set to `tomcat` instead of `tomcat_user`:

-rw------- 1 tomcat    tomcat    253 Aug 10 13:18 context.xml

Shouldn't the owner of this be `tomcat_user` (like server.xml and tomcat-users.xml)?

**Comment by antoineco** [comment]
Nice catch, the problem is [here](https://github.com/antoineco/aco-tomcat/blob/e7b617fae2c296b1911bf5091bfbe4dfcfc1ea20/manifests/context.pp#L31-L32).

I'll have to pass the user and group as parameter. I'm on it

**Comment by joshuabaird** [comment]
Thanks!  I'll test your branch once it's ready.

**Comment by antoineco** [comment]
Ready for review

**Comment by joshuabaird** [comment]
Looks good :+1:
