### ISSUE TITLE
Systemd 'simple' service type does not work with forking startup script

### ISSUE THREAD

**Issue by joshuabaird** [antoineco/aco-tomcat#36]
I'm defining `tomcat` like this:

```
class { '::tomcat':
    package_name   => $tomcat_package,
    version        => $tomcat_package_version,
    catalina_home  => $tomcat_catalina_home,
    admin_webapps  => $tomcat_admin_webapps,
    service_ensure => 'stopped',
    service_enable => false,
  }
```

.. and a `tomcat::instance` like so:

```
tomcat::instance { $instance_name:
    root_path           => $instance_root,
    server_control_port => $instance_control_port,
    ajp_connector       => true,
    ajp_port            => $instance_ajp_port,
    ajp_protocol        => 'AJP/1.3',
    http_connector      => false,
    java_home           => $instance_java_home,
    admin_webapps       => false,
    default_servlet     => true,
}
```

The package that I am using (aspen-tomcat6) is a custom package which installs to /opt/tomcat.  The `aspen-tomcat6.service` unit file is correct (this is supplied by my package):

```
root@aspdv-d1-ap02:/usr/lib/systemd/system# grep -i exec aspen-tomcat6.service
ExecStart=/opt/tomcat/bin/startup.sh
ExecStop=/opt/tomcat/bin/shutdown.sh
```

However, the unit file for the instance has incorrect ExecStart/ExecStop properties which tries to execute a binary that is not there:

```
root@aspdv-d1-ap02:/usr/lib/systemd/system# grep -i exec aspen-tomcat6_aspen.service
ExecStart=/usr/libexec/tomcat/server start
ExecStop=/usr/libexec/tomcat/server stop
```

I'm really not sure how to handle this, since the module probably is not aware of the correct path.  Any ideas or suggestions?

**Comment by antoineco** [comment]
Hey Josh, you should be able to override the instance start and stop commands using the `service_start` and `service_stop` parameters respectively. Let me know if that works in your situation

**Comment by joshuabaird** [comment]
It does, thanks!  I'm now having a problem with `Type=simple` in the systemd unit.  If I change it to `forking`, the service starts and remains started, but with `simple`, systemd kills the process.  Still trying to figure this out.  This is a package built from the Ulyaoth spec.

**Comment by antoineco** [comment]
It is actually a fork in this case, since you start Java via a script the following happens:
`bash --- (fork) ---> process`

If you were starting the Java process directly or inserted a `exec` before running java inside your script (like RedHat's script does if I remember well) it would actually be `Type=simple`.

I should maybe add a parameter for this and/or finally send my PR to Ulyaoth :)

**Comment by joshuabaird** [comment]
I'll look into modifying the startup.sh script possibly in my package unless you already have that PR ready :)  A param may not be a bad thing, either.

**Comment by antoineco** [comment]
The Sysvinit part is ready but I have to take care of systemd OSes as well. An extra parameter is an easy enough workaround though.

**Comment by joshuabaird** [comment]
I can work on the parameter if you would like.

How about `systemd_service_type` for a name?

**Comment by antoineco** [comment]
Perfect 👌

**Comment by joshuabaird** [comment]
Hm, it looks like you default to 'forking' for Fedora, and 'simple' for Suse.  I was going to default the parameter to 'simple.'  Do we need to default to 'forking' for Fedora?

**Comment by antoineco** [comment]
Would be nice to stick to the distribution defaults for people who actually use the distribution packages. A case statement should easily do the job.

**Comment by antoineco** [comment]
Looks like 'forking' would actually cause problems on Fedora with archive installations, since the default start command defined by this module doesn't fork. 

Maybe I need a completely different approach in the end :)

**Comment by joshuabaird** [comment]
Hm, ok.  We can provide 'sane' defaults for the different operating systems, and depend on the user to override if they need.  If we do this, do you think 'simple' would be the sanest default for all operating systems? If so, that cuts the logic down quite a bit.  I'll pause until you figure out how you want to handle this.

**Comment by antoineco** [comment]
Yes 'simple' is probably the most natural default, since it's also the systemd default service type.

I think the following logic would set decent defaults for all supported OSes

Installed from :
- Package
  *\* forking for Fedora, simple for default 
- Archive 
  *\* simple for all

**Comment by joshuabaird** [comment]
Ok - one question.  Should this be a param on `tomcat::instance` or `tomcat`?  I'm thinking `tomcat::instance`?  

UPDATE: Actually, it should probably be on both, which means duplicate logic code between `tomcat` and `tomcat::instance` which seems to be what you have done in the past.

**Comment by joshuabaird** [comment]
#37 opened for review!
