### ISSUE TITLE
PE ignores systemd_service_type param

### ISSUE THREAD

**Issue by ngeorgieff** [antoineco/aco-tomcat#47]
I just noticed in my lab env that PE 2016.2/RHEL 7.2 is ignoring systemd_service_type parameter.
I need to set the parameter to forking but PE ignores it. It works with on RHEL7.2/Puppet OSS.

class { '::tomcat':
  version              => '8.0.23',
  install_from         => 'archive',
  systemd_service_type => 'forking',
  java_home            => '/usr/java/default',
  service_name         => 'tomcat',
  tomcat_user          => 'tomcat',
  admin_webapps        => true,
  create_default_admin => true,
  admin_user           => 'admin',
  admin_password       => 'password',
  config_path          => '/usr/local/tomcat/bin/setenv.sh',
  catalina_home        => '/usr/local/tomcat',
  java_opts            => ['-server', '-Xmx8192M', '-Xms8192M', '-XX:+DoEscapeAnalysis', '-XX:+UseCompressedOops', '-XX:+UseG1GC', '-XX:MaxGCPauseMillis=500', '-XX:+PrintGCDateStamps', '-Xloggc:/var/log/tomcat/gc.log', '-javaagent:/opt/AppDynamics/AppServerAgent/Current/javaagent.jar' ],
  host_autodeploy      => true,
  ajp_connector        => true,
  ajp_port             => 8009,
  ajp_params           => {
            'address'    => '127.0.0.1',
            'packetSize' => 12288 },
}

**Comment by antoineco** [comment]
When you say it's _ignoring_ it, do you mean the value of the variable is `simple` instead?
Could you post the content of `/usr/lib/systemd/system/tomcat8.service` in the affected environment?

**Comment by ngeorgieff** [comment]
The value of the variable is empty:

[root@is-engineering-t01 ~]# cat /usr/lib/systemd/system/tomcat.service
[Unit]
Description=Apache Tomcat Web Application Container
After=syslog.target network.target

[Service]
Type=
EnvironmentFile=-/usr/local/tomcat/bin/setenv.sh
ExecStart=/usr/local/tomcat/bin/catalina.sh start
ExecStop=/usr/local/tomcat/bin/catalina.sh stop
SuccessExitStatus=143
User=
Group=

[Install]
WantedBy=multi-user.target

**Comment by antoineco** [comment]
`$tomcat_user` and `$tomcat_group` are blank as well apparently.

I suspect that's because these variables are not forwarded in the [archive.pp manifest](https://github.com/antoineco/aco-tomcat/blob/master/manifests/service/archive.pp#L12-L15), although they're used in [systemd templates](https://github.com/antoineco/aco-tomcat/blob/d8d8071512a0d9150cdb388d8950ccab980e43db/templates/instance/systemd_unit_rhel.erb#L6). I'm actually surprised this ever worked on Puppet 4! Nice catch.
