### ISSUE TITLE
Module seems not to work with Puppet 3.6.2 due to PUP-1597

### ISSUE THREAD

**Issue by tbe1** [antoineco/aco-tomcat#48]
Hi

first of all thanks for the great tomcat module. Unfortunately there seems to be an issue with the puppet 3.6.2 package on RHEL 7. For example, when I simply try to install tomcat 7 with your module 
I receive the following error:

Error: undefined method ref' for nil:NilClass on node hostname.domain.com
/usr/share/ruby/vendor_ruby/puppet/resource/catalog.rb:534:in block in to_catalog'
/usr/share/ruby/vendor_ruby/puppet/resource/catalog.rb:522:in each'
/usr/share/ruby/vendor_ruby/puppet/resource/catalog.rb:522:in to_catalog'
/usr/share/ruby/vendor_ruby/puppet/resource/catalog.rb:410:in to_resource'
/usr/share/ruby/vendor_ruby/puppet/parser/compiler.rb:23:in compile'
/usr/share/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:95:in block (2 levels) in compile'
/usr/share/ruby/vendor_ruby/puppet/util/profiler/none.rb:6:in profile'
/usr/share/ruby/vendor_ruby/puppet/util/profiler.rb:43:in profile'
/usr/share/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:93:in block in compile'
/usr/share/ruby/vendor_ruby/puppet/util.rb:161:in block in benchmark'
/usr/share/ruby/benchmark.rb:296:in realtime'
/usr/share/ruby/vendor_ruby/puppet/util.rb:160:in benchmark'
/usr/share/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:92:in compile'
/usr/share/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:52:in find'
/usr/share/ruby/vendor_ruby/puppet/indirector/indirection.rb:201:in find'
/usr/share/ruby/vendor_ruby/puppet/application/apply.rb:214:in block in main'
/usr/share/ruby/vendor_ruby/puppet/context.rb:64:in override'
/usr/share/ruby/vendor_ruby/puppet.rb:234:in override'
/usr/share/ruby/vendor_ruby/puppet/application/apply.rb:190:in main'
/usr/share/ruby/vendor_ruby/puppet/application/apply.rb:151:in run_command'
/usr/share/ruby/vendor_ruby/puppet/application.rb:371:in block (2 levels) in run'
/usr/share/ruby/vendor_ruby/puppet/application.rb:477:in plugin_hook'
/usr/share/ruby/vendor_ruby/puppet/application.rb:371:in block in run'
/usr/share/ruby/vendor_ruby/puppet/util.rb:479:in exit_on_fail'
/usr/share/ruby/vendor_ruby/puppet/application.rb:371:in run'
/usr/share/ruby/vendor_ruby/puppet/util/command_line.rb:137:in run'
/usr/share/ruby/vendor_ruby/puppet/util/command_line.rb:91:in execute'
/usr/bin/puppet:8:in main'

**Installed Packages**
RHEL 7 ships with puppet version 3.6.2.
Name        : puppet
Arch        : noarch
Version     : 3.6.2
Release     : 4.el7sat

This seems to be related to https://tickets.puppetlabs.com/browse/PUP-1597 - after removing the leading '::' for all contains in manifests/init.pp the module works as expected.
-init.pp:  contain ::tomcat::install
-init.pp:  contain ::tomcat::service
-init.pp:  contain ::tomcat::config
-init.pp:    contain ::tomcat::log4j
-init.pp:    contain ::tomcat::extras
-init.pp:    contain ::tomcat::firewall

+init.pp:  contain tomcat::install
+init.pp:  contain tomcat::service
+init.pp:  contain tomcat::config
+init.pp:    contain tomcat::log4j
+init.pp:    contain tomcat::extras
+init.pp:    contain tomcat::firewall

**Comment by antoineco** [comment]
Thanks for reporting 👍 This seems indeed related.

Leading `::` are actually not necessary anymore and can be removed safely. I'll drop them from the module.

**Comment by antoineco** [comment]
I'll have to be a bit careful with that and ask you to confirm something before pushing my changes, because I fear that one might run into trouble if this `tomcat` class is wrapped inside a higher level class which is also called `tomcat`.

Example:

``` puppet
class role::tomcat {
  class { '::tomcat': }
}
include role::tomcat
```

Could you execute that in your environment (Puppet 3.6) and make sure it runs without error?

**Comment by tbe1** [comment]
I executed your example in my puppet 3.6 environment without getting an error.
