### ISSUE TITLE
Change limits for systemd managed instances

### ISSUE THREAD

**Issue by ghost** [antoineco/aco-tomcat#50]
Hello,

The mechanism configuring limits are very different between init.d and systemd. In our old environment not managed with puppet we changed limits in /etc/security/limits.conf. This doesn't work for systemd.

To change limits entries must added to service definition:

```
[Service]
    LimitNOFILE=12345
```

I have no time testing with init.d systems. So my options are:
1. Add a custom systems options parameter for systemd
2. Add a parameter for custom service files

I prefer adding custom systemd parameters.

Regards,

Frank

**Comment by antoineco** [comment]
Hi Frank,

Have you considered using a systemd drop-in? This would let you override any systemd setting without having to create a class parameter explicitly in the tomcat module.

Example:

``` puppet
file { '/etc/systemd/tomcat.service.d/limits.conf' :
  ensure  => present,
  content => "[Service]
  LimitNOFILE=12345"
} ~>
exec { 'refresh systemd on limits change':
  command => '/usr/bin/systemctl daemon-reload'
}
```

After running this manifest you should see your limits added to the `tomcat` service definition when executing `systemctl cat tomcat`.

**Comment by ghost** [comment]
Thank you. This is perfect.
