### ISSUE TITLE
deployment without further management

### ISSUE THREAD

**Issue by nomoresecrets** [antoineco/aco-tomcat#53]
Hi there,

I'd like to know if there's a chance to use this module to deploy Tomcat and not managing anything further?

I'd like to use it for a test environment with puppet-defined default settings. But the guys using tomcat should be able to change the settings without puppet overwriting the changes. Same goes for manually stopping the service.

Thanks,

Denny

**Comment by antoineco** [comment]
Hi @nomoresecrets, I think what you ask has more to do with the way you use Puppet than the module itself.

If you have a Puppet agent installed in you test environment and this agent polls the master every x minutes, then yes changes will be overwritten.

If instead you just pull this module and execute something like `puppet apply tomcat.pp` (you have to create this manifest yourself of course) then your installation will be deployed locally once, and remain unmanaged after the run.

Does it answer your question?
