### ISSUE TITLE
server.xml stanza ordering changes

### ISSUE THREAD

**Issue by glennhuxtable** [antoineco/aco-tomcat#56]
I am using v1.3.2 of your tomcat module, puppet version 3.7.5.

I noticed that the order of parameters in some server.xml kept being rewritten with each puppet run, potentially causing tomcat restarts etc.

It appears that the order of items in a hash are not being reported consistently. I got around this by sorting the hash elements, before using them.

For example, in 090_host.erb
   <Host name="<%= @host_name %>"<% if @host_params_real and ! @host_params_real.empty? %>
             <%- @host_params_real.each_pair do |attrib, value| -%>
            <%= attrib %>="<%= value %>"<% if attrib == @host_params_real.keys.last %>><% end %>
             <%- end -%>
           <%- else -%>

> ```
>        <%- end -%>
> ```

I changed this to:
      <Host name="<%= @host_name %>"<% if @host_params_real and ! @host_params_real.empty? %>
             <%- @host_params_real.sort.each do |pair | -%>
            <%= pair[0] %>="<%= pair[1] %>"
             <%- end -%>
            >
           <%- else -%>

> ```
>        <%- end -%>
> ```

resulting in a consistent, sorted, ordering of parameters in the Host name stanza.
likewise I updated 010_listeners.erb, 050_connector.erb, 053_connectors.erb, 060_engine.erb, 090_host.erb

Am I missing something in regard to the ordering of parameters in these stanzas. I know the order should not matter to tomcat, but Puppet seems to want to rewrite the server.xml file every time it runs depending on the ordering returned by 'each_pair'.

**Comment by glennhuxtable** [comment]
well, that didn't go well. looks like the issues editor ate half of my issue.

What I tried to say that that I replaced:
             <%- @host_params_real.each_pair do |attrib, value| -%>
            <%= attrib %>="<%= value %>"<% if attrib == @host_params_real.keys.last %>><% end %>
             <%- end -%>

with 
             <%- @host_params_real.sort.each do |pair | -%>
             <%= pair[0] %>="<%= pair[1] %>"
             <%- end -%>

to get the parameters in the Host stanza in a consistent (sorted) order, eg:
      <Host name="localhost"
            appBase="/usr/share/tomcat7/webapps"
            autoDeploy="true"
            unpackWARs="true"
            xmlNamespaceAware="false"
            xmlValidation="false"
            >

Unless later versions of Puppet/Ruby (I'm running 1.8.7) automagically sort the result of 'each_pair', I don't understand how this code  does not cause Puppet to have conniptions.

**Comment by antoineco** [comment]
Unfortunately Ruby 1.8 is not supported by this module, it was even deprecated by Puppet a while ago. You could easily fix that by using the "PC1" official repos from Puppet, which include their own supported version of Ruby, installed in /opt/puppet and used exclusively by Puppet.

See #15
