### ISSUE TITLE
Ubuntu 14.04 - Tomcat 7.0.52-1

### ISSUE THREAD

**Issue by Behner** [antoineco/aco-tomcat#59]
Ran into an issue where I had to set verison => '7.0.52-1', otherwise it could not find the correct packages to install by default... it was trying to find "7.0.52-1ubuntu0.6" but "7.0.52-1ubuntu0.7" is now available in the repos. I see that is "7.0.52-1ubuntu0.6" referenced here: https://github.com/antoineco/aco-tomcat/search?utf8=%E2%9C%93&q=%227.0.52-1ubuntu0.6%22

Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install tomcat7-admin=7.0.52-1ubuntu0.6' returned 100: Reading package lists...

Thanks for module!! Hope this helps.

**Comment by antoineco** [comment]
Indeed I try to keep up with the updates but sometimes I lag a bit ;) Thanks for pointing this out, I'll send an uprated list soon!
