### ISSUE TITLE
RHEL 7 - systemd service file is not being created

### ISSUE THREAD

**Issue by markfaine** [antoineco/aco-tomcat#67]
I'm not getting any errors that would indicate that it is failing to create the service file but when it attempts to start it fails:

```
Error: Execution of 'journalctl -n 50 --since '5 minutes ago' -u tomcat --no-pager' returned 1: -- Logs begin at Tue 2016-11-29 14:30:36 CST, end at Fri 2016-12-02 14:22:08 CST. --
Error: /Stage[main]/Tomcat::Service::Package/Service[tomcat]/ensure: change from stopped to running failed: Execution of 'journalctl -n 50 --since '5 minutes ago' -u tomcat --no-pager' returned 1: -- Logs begin at Tue 2016-11-29 14:30:36 CST, end at Fri 2016-12-02 14:22:08 CST. --
```
So, I tried just starting it manually to look at log output:

```
sudo systemctl start tomcat
Failed to start tomcat.service: Unit tomcat.service failed to load: No such file or directory.
```

So, I checked where the service file should be created (/usr/lib/systemd/system) and did not find it.

The relevant parameters are set like:

```
service_name               => 'tomcat',                                                                                                                                                                   
service_enable             => true,                                                                                                                                                                       
service_ensure             => running,                                                                                                                                                                    
systemd_service_type       => 'simple',                                                                                                                                                                  
restart_on_change          => true, 
service_start                  => "TZ=CST6CDT ${dctm_tomcat::jsvc_bin} -user ${tomcat::tomcat_user}\                                                                                                          
     -home ${::java_home} ${tomcat::java_opts} -outfile ${tomcat::catalina_home}/logs/catalina.out  \                                                                                                              
     -errfile ${tomcat::catalina_home}/logs/catalina.err ${tomat::catalina_opts} -cp ${dctm_tomcat::classpath} \                                                                                                   
     org.apache.catalina.startup.Bootstrap",                                                                                                                                                                       
service_stop               => "${dctm_tomcat::jsvc_bin} -stop -pidfile ${tomcat::catalina_pid} org.apache.catalina.startup.Bootstrap", 
```

**Comment by antoineco** [comment]
Did you install tomcat using RHEL's repository or Apache's archive?

**Comment by markfaine** [comment]
Neither, a custom built RPM.

**Comment by antoineco** [comment]
Ah, that's why! The module expects all packages to be compliant and ship with their own init script / unit, otherwise it would overwrite distro specific system files, which are in most cases specific for a reason. In general I prefer to focus on the service configuration, and let the OS deal with OS things (log rotation, init, ...)

What is the use case for packaging tomcat without a way to start it as a service? (just curious)

**Comment by markfaine** [comment]
It's a really simple package for Tomcat 8, originally created for RHEL 6 but modified for RHEL7.  At the time it was built (a few months ago) I was maintaining the init script as a template in puppet.  The justification was that another group wanted to use it too, but their init script requirements were much different than ours so we decided that we'd just keep it in puppet and install as a dependency for the package.  That way they could maintain their own init script in their puppet code and use hiera to control which init script was used.

I can modify the package to add a service file, that's no big deal.  It just looked like from the code there were templates for init and service files, so it didn't occur to me that they would need to be in the package.

I like your module better than the way I was doing it, since now I have a single file with all of my tomcat configuration in it, instead of several different files and templates.   There is a bit of an up-front cost in switching but I think in the long run this is a much better way to manage tomcat.

**Comment by antoineco** [comment]
Alright, I didn't have this use case in mind, thanks for the explanation.

The module is quite opinionated regarding startup scripts, it tries to use what ships with the OS package in order to leverage multi-instance setups in a clean way. By leveraging these I just have to create symlinks in order to enable multiple tomcat services using the same base installation (the way described and recommended by Apache)

Then there is the other case where the user wants a specific version, which comes as a tar.gz archive and does not contain an init script. Here I have to provide something myself to make tomcat usable, therefore I deploy a generic systemd unit and very minimal script.

And now there is your case: a package which expects to behave like an archive :)

Let me think about how to work around that. Maybe a `force_init` parameter which forces the deployment of the init script whatever the installation medium?

**Comment by markfaine** [comment]
@antoineco have you decided if you are going to add force_init?  I really appreciate how much you've helped me so I don't want to add any pressure but it would be awesome for me if you did add it.  I might even make my target dates on this puppet configuration.

**Comment by antoineco** [comment]
Hi Mark, I just pushed the new class parameter to the branch [`force_init`](https://github.com/antoineco/aco-tomcat/tree/force_init). It should work without any further modification, assuming that the `catalina_home` parameter is set properly in case your package does not use the distro's default ("/usr/share/tomcat" on RHEL7)

**Comment by antoineco** [comment]
@markfaine the commit 03daa27 should allow you to deploy your package reliably using just the following 2 parameters:

```puppet
class { 'tomcat':
  force_init    => true,
  catalina_home => '/path/to/tomcat/directory'
}
```

The module should then do the right things by itself.
 
Could you confirm it works as you expected or provide feedback for improvement before I merge?

**Comment by antoineco** [comment]
ping @markfaine

**Comment by markfaine** [comment]
Thanks!  This works.
