### ISSUE TITLE
Question:  Proxy for enable extras

### ISSUE THREAD

**Issue by markfaine** [antoineco/aco-tomcat#68]
All of my servers are behind a firewall with the only access out through an http/https proxy.   I can certainly enable this proxy using:

```
export http_proxy=<my proxy url:port>
export https_proxy=<my proxy url:port>
```

However, then everything tries to use the proxy, which causes different problems.   I've solved this problem with external yum repos by setting an option that is specific to each individual repo,  I'd like to set proxies in an opt-in sort of way instead of an opt-out, and I hate to rely on the server environment configuration with puppet. 

The problem comes up when I'm trying to use enable_extras and it times out since no proxy is available.
Do you have any ideas for how I can get around this problem?

**Comment by antoineco** [comment]
How about exporting these variables just in the context of the Puppet agent? If you're running the Puppet agent as a service you can set these variables in a [systemd drop-in](https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html), this way they don't affect the rest of the system.

Another more cumbersome approach would be to mirror all the extra libs you need on a server inside your corporate network, and fetch them from a custom URL. This is not supported yet but easy to implement (cf my oracle_java module)

**Comment by markfaine** [comment]
I think I found a way around it by using no_proxy environment variable.  I am basically using a proxy by default but excluding local networks, localhost, etc.  It seems to be working okay.  The environment variable is set in a file (deployed by puppet) in /etc/profile.d that is sourced system-wide.

**Comment by antoineco** [comment]
Great, glad you found a solution that works for you. Thanks for sharing the details!
