### ISSUE TITLE
Configurable Log Directory

### ISSUE THREAD

**Issue by hanej** [antoineco/aco-tomcat#7]
Please allow specifying the log directory instead of having it go to /var/log.

**Comment by antoineco** [comment]
Done in commit 1059230c9c8cf4c1c42cf9d64f67031f3e982175

**Comment by hanej** [comment]
I'm getting an error when trying to deploy 2 instances with the same log_path.  We need all logs to go into /app/logs and from there each instance has their own log file.  Maybe the best way to handle this is to check to see if the resource is defined before trying to declare it again.

Error: Cannot alias File[instance puppetdev6_2 logs directory] to ["/app/logs"] at /etc/puppet/modules/tomcat/manifests/instance.pp:550; resource ["File", "/app/logs"] already declared at /etc/puppet/modules/tomcat/manifests/instance.pp:550

Here is my test.

```
class { 'tomcat':
  service_ensure => 'stopped',
  service_enable => false,
}
tomcat::instance { 'puppetdev6_1':
  root_path        => '/app/domains/prd1_webstr',
  catalina_base    => "/app/domains/prd1_webstr/${::hostname}_1",
  log_path         => '/app/logs',
  service_name     => "prd1_webstr_${::hostname}_1",
}
tomcat::instance { 'puppetdev6_2':
  root_path        => '/app/domains/prd1_webstr',
  catalina_base    => "/app/domains/prd1_webstr/${::hostname}_2",
  log_path         => '/app/logs',
  service_name     => "prd1_webstr_${::hostname}_2",
}
```

**Comment by antoineco** [comment]
Indeed, I forgot to take this into account. Your solution is the right one, expect a new release later today.

**Comment by hanej** [comment]
Also if the log_path happens to equal ${catalina_base_real}/logs then you can skip creating the symlink.

**Comment by antoineco** [comment]
I think these changes should do, could you check it out? Feel free to close the ticket if you're satisfied with the result.
