### ISSUE TITLE
Management of security-constraints

### ISSUE THREAD

**Issue by antoineco** [antoineco/aco-tomcat#82]
Request received from @alexmeise per email:

> Is there a way to manage security constrains via your module? Something like inserting them into web.xml withouth having to use a template.

The user wants to generate a configuration similar to this one:

```xml
<security-constraint>
    <display-name>sample</display-name>
    <web-resource-collection>
        <url-pattern>*.gif</url-pattern>
    </web-resource-collection>
    <auth-constraint>
       <role-name>authenticated</role-name>
    </auth-constraint>
</security-constraint>
```

**Comment by antoineco** [comment]
@alexmeise I pushed a new branch with a [relevant example](https://github.com/antoineco/aco-tomcat/pull/84/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8). Could you please give it a try and tell me if you would like to change something?

**Comment by alexmeise** [comment]
@antoineco this looks perfect! thanks a lot. So far I did not have time to test but I will come back to you.

**Comment by alexmeise** [comment]
Thanks a lot man
