### ISSUE TITLE
Add a subentry for Context in Host entry of server.xml

### ISSUE THREAD

**Issue by HerveMARTIN** [antoineco/aco-tomcat#85]
In server.xml, we add a subentry in Host to specify the Context of the application.
For example : 
`<Host name="localhost">
    <Context path="" docBase="..." crossContext="true"/>
</Host>`
If you're ok i'll make a PR.

**Comment by antoineco** [comment]
Closed by #86

**Comment by HerveMARTIN** [comment]
@antoineco did you rename $host_context param into $contexts?
I had chosen this naming to be clear that it has nothing to do with context.xml.
I would have liked, at least, to be informed.
Switching back from my fork to the last release broke it here...

**Comment by antoineco** [comment]
@HerveMARTIN yes, I did it to keep a consistent naming scheme across the class parameters (eg. `valves` is not called `host_valves`). `host_*` is already reserved for the `<Host>` node attributes.

I posted a comment pointing to the new version, where changes are documented: https://github.com/antoineco/aco-tomcat/pull/86#issuecomment-338277138.
