### ISSUE TITLE
Support Red Hat 5

### ISSUE THREAD

**Issue by hanej** [antoineco/aco-tomcat#9]
Please support managing Tomcat on Red Hat 5 systems.  As far as I know this only needs to be adjusted in params.pp.

**Comment by antoineco** [comment]
Shouldn't be too hard, I'm on it!

**Comment by hanej** [comment]
You are awesome!  Thank you.  This module rocks!

**Comment by antoineco** [comment]
I hope it does! Just out of curiosity, what version are you planning to run on your CentOS 5? I can only find tomcat5 (5.5.23) in the repos, and jpackage5 seems broken.

**Comment by hanej** [comment]
We actually use the archives only.  Red Hat is too behind in their repo.

**Comment by antoineco** [comment]
Good, makes my task easier :+1:

**Comment by antoineco** [comment]
It doesn't play too nice with Ruby 1.8.7 on my dev setup, some elements in the `server.xml` are generated in a different order for every Puppet run. Can you provide some feedback?

**Comment by antoineco** [comment]
@hanej did you find the time to test this?

**Comment by hanej** [comment]
Sorry.  I didn't realize this was ready.  I'll start testing.

**Comment by antoineco** [comment]
Feature available in v1.0.0, released today.

As I said, it will require a recent Ruby version (probably 1.9.3, if not above) to avoid the random hash merging behavior.
