### ISSUE TITLE
Add a parameter to not manage the service

### ISSUE THREAD

**Issue by HerveMARTIN** [antoineco/aco-tomcat#95]
Hello,
We use an orchestrator to deploy our tomcat app, and for some other reason we need that this module be able to not manage the tomcat service.
I'll join a PR to add a parameter and a condition to incluse or not the service resource in the catalog.

**Comment by HerveMARTIN** [comment]
Sorry i've just seen this article that pointed me a simpler solution : https://ask.puppet.com/question/2598/enable-a-service-on-boot-but-dont-ensure/

**Comment by HerveMARTIN** [comment]
Well I found this code in init.pp that forbid using service_ensure => undef to not change the state of the service...
Why not using Puppet types to restrict authorized values?

**Comment by antoineco** [comment]
Yeah you're actually right, it's a bit stupid to validate the value of this parameter if `undef` is a valid option.

**Comment by antoineco** [comment]
Closed by #96
